name: CloudGame CI

on:
  push:
    branches: [ "main" ]

jobs:
  validate-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Vérifier la présence du frontend
        run: test -f frontend/index.html

      - name: Vérifier le nom du projet
        run: grep -q "CloudGame 2048" frontend/index.html

      - name: Vérifier les endpoints API
        run: grep -q "u81b3h1eo2.execute-api" frontend/index.html