name: CloudGame CI

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Vérifier le frontend
        run: |
          test -f frontend/index.html

      - name: Vérifier la présence d'un titre HTML
        run: |
          grep -i "<title>" frontend/index.html

      - name: Vérifier que l'API est configurée
        run: |
          grep -i "execute-api" frontend/index.html

      - name: Vérifier la syntaxe HTML
        run: |
          grep -i "</html>" frontend/index.html