name: CloudGame CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy-cloudgame:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Récupération du dépôt
        uses: actions/checkout@v4

      - name: 🔐 Connexion à AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: ✅ Vérification du frontend CloudGame
        run: |
          test -f frontend/index.html

      - name: 🚀 Déploiement du frontend CloudGame
        run: |
          aws s3 sync frontend/ s3://${{ secrets.S3_BUCKET }} --delete

      - name: 🎉 Déploiement terminé
        run: echo "CloudGame 2048 déployé avec succès !"